### ISSUE TITLE
Swift 2.3 compatibility

### ISSUE THREAD

**Issue by Flox06** [RamonGilabert/Walker#1]
Hi ! 

Can you please consider adding a swift 2.3 compatibility branch ?

BTW, thanks for your work 👍

**Comment by RamonGilabert** [comment]
Hey @Flox06!

Thanks for filing issue and for using Walker! The library has been updated to Swift 3 in master and with the release of version `0.10.0`, sadly, I won't be making a Swift 2.3 branch now that master is ahead and I use Swift 3 in internal projects.

However, feel free to add a PR with your branch! 😊

**Comment by Flox06** [comment]
Yeap, understood, finally forked it. 
We only needed it to deal with xcode8 and legacy swift 2.3 mode (cause our project is not yet swift3 ready).
Will be soon migrated to swift3 so...
I don't want to add a PR, cause I've fixed the swift 2.3 compatibility very... roughly !

Thanks ;)
